### ISSUE TITLE
Error when reading binary file

### ISSUE THREAD

**Issue by zebulasampedro** [SandstoneHPC/sandstonehpc-project#99]
The following error occurred when trying to access a binary file:

```
ERROR:tornado.application:Uncaught exception GET /user/vagrant/a/filesystem/files/%2Fhome%2Fvagrant%2F.Xauthority/contents/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='172.28.128.3', method='GET', uri='/user/vagrant/a/filesystem/files/%2Fhome%2Fvagrant%2F.Xauthority/contents/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'X-Forwarded-Host': '172.28.128.3', 'X-Forwarded-Port': '443', 'X-Forwarded-For': '172.28.128.1', 'Connection': 'close', 'Accept': 'application/json, text/plain, */*', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'Host': '172.28.128.3', 'X-Forwarded-Proto': 'https', 'Cookie': 'jupyter-hub-token-vagrant="2|1:0|10:1498765148|25:jupyter-hub-token-vagrant|44:ZDliNDM2Yjk2NmQwNDNjZmJjMmQyM2FmNjY5MzNjN2Y=|e6b30b322d4c9e1f1a94fe823f623be4cc7ee518b88efb08dca662e719b7bb99"; _xsrf=2|89ac0f3f|3db02a324b2ba03b8b062803c9c39c61|1498762318; user="2|1:0|10:1498765148|4:user|12:dmFncmFudA==|b94af9709af3516266567890c631183f32b7bf9a5188e53dd0cc1f4d7473166b"', 'X-Xsrftoken': '2|89ac0f3f|3db02a324b2ba03b8b062803c9c39c61|1498762318', 'Referer': 'https://172.28.128.3/user/vagrant/'})
Traceback (most recent call last):
  File "/opt/sandstone-project/venv-sandstone/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/sandstone-project/sandstone-ide/sandstone/lib/decorators.py", line 21, in wrapper
    return method(self, *args, **kwargs)
  File "/opt/sandstone-project/sandstone-ide/sandstone/lib/filesystem/handlers.py", line 280, in get
    self.write({'filepath':filepath,'contents': contents})
  File "/opt/sandstone-project/venv-sandstone/lib/python2.7/site-packages/tornado/web.py", line 692, in write
    chunk = escape.json_encode(chunk)
  File "/opt/sandstone-project/venv-sandstone/lib/python2.7/site-packages/tornado/escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 40: invalid start byte
ERROR:tornado.access:500 GET /user/vagrant/a/filesystem/files/%2Fhome%2Fvagrant%2F.Xauthority/contents/ (127.0.0.1) 8.98ms
```

This encoding error is observed _(unsurprisingly)_ for files of type `application/octet-stream; charset=binary`.

**Comment by zebulasampedro** [comment]
In this situation, the handlers in the FS API should check MIME info before reading or writing from a file and just return a 204.
